### ISSUE TITLE
exa not installed ? Alias not working? 

### ISSUE THREAD

**Issue by yabur** [xcad2k/dotfiles#1]
![image](https://user-images.githubusercontent.com/16948225/130902767-ff369bfc-02ec-4d06-948a-8f519d1bf9e8.png)

**Comment by cryodream** [comment]
Just in case someone else, like me (Linux newb) has trouble with installing exa in WSL2 Ubuntu 20.04 LTS.
If you get this when trying to install
```bash
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package exa
```
Do this
```bash
wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
sudo apt-get install ./exa_0.9.0-4_amd64.deb
```
I found this solution here: https://askubuntu.com/a/1290552

**Comment by xcad2k** [comment]
Remove the annoying text, when exa isn't installed.
