### ISSUE TITLE
starship.toml not formatted with utf-8 powershell error

### ISSUE THREAD

**Issue by XanNava** [xcad2k/dotfiles#3]
Not entirely an issue on your side, but maybe a note for future people trying to use this. I was getting an error when using the file on windows terminal(powershell) as it seems it needs to be formatted as ntf-8. I simply opened it up in sublime and saved with encoding as ntf-8. Hopefully helps someone else in the future.

**Comment by xcad2k** [comment]
Which powershell version did you try this with?

**Comment by avoxm** [comment]
Same issue here. Icons are broken.
