### ISSUE TITLE
Which icons/fonts did you use?

### ISSUE THREAD

**Issue by TonyBostonTB** [xcad2k/dotfiles#4]
Would you mind adding the fonts and icons being used to the README?
Cheers

**Comment by xcad2k** [comment]
Great suggestion, I'll add a better description in the readme file including the fonts, icons, and maybe some screenshots. Thanks mate!

**Comment by tcamargo** [comment]
Your starship config is using some unknown characters in renamed and stashed git statuses. Tried to use a couple of nerd fonts, including Hack.
<img width="459" alt="image" src="https://github.com/ChristianLempa/dotfiles/assets/52097/91f27983-664e-4979-a8c5-d6debcffd86e">
