### ISSUE TITLE
zsh: command not found: exa ?

### ISSUE THREAD

**Issue by najibveto** [xcad2k/dotfiles#6]
hello,
thank you for your time and for your awesome tutorial.
i tried your configuration and when i try to use the ls command, i got this error:
![image](https://user-images.githubusercontent.com/77666435/151929397-856ec209-4eee-471a-abd1-d3a86ffe7846.png)

so in your opinion, how i can solve it?
should i install exa?

**Comment by xcad2k** [comment]
Yeah, you just need to install exa https://github.com/ogham/exa
